#pragma config(Sensor, port5,  color4,         sensorVexIQ_LED)
#pragma config(Sensor, port6,  color1,         sensorVexIQ_LED)
#pragma config(Sensor, port10, gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, color2,         sensorVexIQ_LED)
#pragma config(Sensor, port12, color3,         sensorVexIQ_LED)
#pragma config(Motor,  motor2,          armright,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          rightdrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor4,          strafe,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          armleft,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          leftdrive,     tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float e = 2.71828459045;

void driveReset() {
	setMotorSpeed(leftdrive, 0);
	setMotorSpeed(rightdrive, 0);
	resetMotorEncoder(rightdrive);
	resetMotorEncoder(leftdrive);
}

void setup() {
	resetMotorEncoder(armright);
	resetMotorEncoder(armleft);
	resetMotorEncoder(strafe);
	resetMotorEncoder(rightdrive);
	resetMotorEncoder(leftdrive);
	setGyroSensitivity(gyro, gyroNormalSensitivity);
	resetGyro(gyro);
}

void forward(int ticks, int speed) {
	setMotorSpeed(rightdrive, speed);
	setMotorSpeed(leftdrive, speed);
	sleep(ticks);
	setMotorSpeed(rightdrive, 0);
	setMotorSpeed(leftdrive, 0);
}

void turnLeft(int degrees, int speed) {
	setup();
	while (abs(getGyroDegrees(gyro)) < degrees) {
		setMotorSpeed(leftdrive, -speed);
		setMotorSpeed(rightdrive, speed);
	}
	driveReset();
}

void turnRight(int degrees, int speed) {
	setup();
	while (abs(getGyroDegrees(gyro)) < degrees) {
		setMotorSpeed(leftdrive, speed);
		setMotorSpeed(rightdrive, -speed);
	}
	driveReset();
}

void s(int ticks, int speed) {
	driveReset();
	moveMotorTarget(strafe, ticks, speed);
}

void arm(int time, int speed) {
	setup();
	setMotorSpeed(armleft, speed);
	setMotorSpeed(armright, speed);
	sleep(time);
	setMotorSpeed(armleft, 0);
	setMotorSpeed(armright, 0);
}

task main() {
	setTouchLEDColor(color1, colorViolet);
	setTouchLEDColor(color2, colorViolet);
	setTouchLEDColor(color3, colorViolet);
	setTouchLEDColor(color4, colorViolet);
	setup();
	//forward(180, 40);
	//turnRight(90, 40);
	s(-550, 60);
	sleep(1200);
	forward(400, 100);
	sleep(500);
	turnRight(30, 20);
	forward(1000, 100);
	arm(1000, 80);
	setMotorSpeed(strafe, -60);
	sleep(1700);
	setMotorSpeed(strafe, 0);
	forward(600, 100);
	arm(500, -80);
	forward(550, -50);
	turnRight(185, 25);
	arm(1000, -80);
	forward(600, 100);
	arm(1000, 80);
	forward(1100, 100);
	turnRight(75, 25);
	forward(1600, 100);
	arm(400, -80);
	forward(200, -60);
}
