#pragma config(Sensor, port2,  color2,         sensorVexIQ_LED)
#pragma config(Sensor, port3,  color3,         sensorVexIQ_LED)
#pragma config(Sensor, port4,  color5,         sensorVexIQ_LED)
#pragma config(Sensor, port7,  color4,         sensorVexIQ_LED)
#pragma config(Sensor, port8,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port9,  color1,         sensorVexIQ_LED)
#pragma config(Motor,  motor1,          dropper,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          frontarm,      tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          spintake,      tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         leftdrive,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor11,         backarm,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightdrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int t = 0;

int leftspeed;
int rightspeed;

bool backarmMovement = false;

bool previousFramePressed = false;
bool previousFramePressedEUp = false;
bool previousFramePressedEDown = false;

int spintakeState = 0;

void color(unsigned short c) {
	setTouchLEDColor(color1, c);
	setTouchLEDColor(color2, c);
	setTouchLEDColor(color3, c);
	setTouchLEDColor(color4, c);
	setTouchLEDColor(color5, c);
}

void setup() {
	setMotorSpeed(dropper, 0);
	setMotorSpeed(frontarm, 0);
	setMotorSpeed(spintake, 0);
	setMotorSpeed(leftdrive, 0);
	setMotorSpeed(rightdrive, 0);
	setMotorSpeed(backarm, 0);
	resetMotorEncoder(dropper);
	resetMotorEncoder(frontarm);
	resetMotorEncoder(spintake);
	resetMotorEncoder(leftdrive);
	resetMotorEncoder(rightdrive);
	resetMotorEncoder(backarm);
	resetGyro(gyro);
}

bool gear = true;

task drop() {
	while (true) {
		if (getJoystickValue(BtnFUp) == 1) {
			setMotorSpeed(dropper, -80);
			sleep(500);
			setMotorSpeed(dropper, 100);
			sleep(300);
			setMotorSpeed(dropper, 5);
		}
	}
}

task back() {
	while (true) {
		if (getJoystickValue(BtnRDown) == 1 && getJoystickValue(BtnRUp) == 0) {
			backarmMovement = true;
			setMotorSpeed(backarm, -100);
			sleep(800);
			setMotorSpeed(backarm, 0);
			backarmMovement = false;
		} else if (getJoystickValue(BtnRUp) == 1 && getJoystickValue(BtnRDown) == 0) {
			setMotorSpeed(backarm, 100);
		} else {
			setMotorSpeed(backarm, 0);
		}
	}
}

task main() {
	setup();
	startTask(drop);
	startTask(back);
	while (true) {
		t++;
		color(t % 300);
		displayTextLine(2, "%d", getMotorCurrent(spintake));
		if (getJoystickValue(BtnLUp) == 1 && getJoystickValue(BtnLDown) == 0) {
			setMotorSpeed(frontarm, 100);
		} else if (getJoystickValue(BtnLDown) == 1 && getJoystickValue(BtnLUp) == 0) {
			setMotorSpeed(frontarm, -100);
		} else {
			setMotorSpeed(frontarm, 0);
		}

		if (getJoystickValue(BtnEDown) == 0 && previousFramePressedEDown) {
			previousFramePressedEDown = false;
		} else if (getJoystickValue(BtnEDown) == 1 && !previousFramePressedEDown) {
			spintakeState--;
			previousFramePressedEDown = true;
		}

		if (getJoystickValue(BtnEUp) == 0 && previousFramePressedEUp) {
			previousFramePressedEUp = false;
		} else if (getJoystickValue(BtnEUp) == 1 && !previousFramePressedEUp) {
			spintakeState++;
			previousFramePressedEUp = true;
		}

		if (getJoystickValue(BtnLUp) == 1 || getJoystickValue(BtnLDown) == 1) {
			spintakeState = 20000;
		}

		if (spintakeState == 20000) {
			spintakeState = 0;
		} else if (spintakeState < -1) {
			spintakeState = -1;
		} else if (spintakeState > 1) {
			spintakeState = 1;
		}

		if (getJoystickValue(BtnFDown) == 0 && previousFramePressed) {
			previousFramePressed = false;
		} else if (getJoystickValue(BtnFDown) == 1 && !previousFramePressed) {
			gear = !gear;
			previousFramePressed = true;
		}

		leftspeed = pow(getJoystickValue(ChA), 3) / 10000 * (gear ? 1 : 0.6) * (abs(getJoystickValue(ChA)) > 10 ? 1 : 0);
		rightspeed = pow(getJoystickValue(ChD), 3) / 10000 * (gear ? 1 : 0.6) * (abs(getJoystickValue(ChD)) > 10 ? 1 : 0);

		setMotorSpeed(leftdrive, leftspeed);
		setMotorSpeed(rightdrive, rightspeed);
		setMotorSpeed(spintake, 100 * spintakeState);
	}
}
