#pragma config(Sensor, port5,  color4,         sensorVexIQ_LED)
#pragma config(Sensor, port6,  color1,         sensorVexIQ_LED)
#pragma config(Sensor, port10, gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, color2,         sensorVexIQ_LED)
#pragma config(Sensor, port12, color3,         sensorVexIQ_LED)
#pragma config(Motor,  motor2,          armright,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          rightdrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor4,          strafe,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          armleft,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          leftdrive,     tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float e = 2.71828459045;
int k = 4000;

void setup() {
	resetMotorEncoder(armright);
	resetMotorEncoder(armleft);
	resetMotorEncoder(strafe);
	resetMotorEncoder(rightdrive);
	resetMotorEncoder(leftdrive);
	setGyroSensitivity(gyro, gyroNormalSensitivity);
	resetGyro(gyro);
}

int map(int value) {
	int output;
	if (value > 0) {
		output = (((120 / (1 + 0.05 * pow(e, -0.072 * (value - 90))) - 0.764) / 1.13576986016) + 0.035);
	} else if (value < 0) {
		output = -(((120 / (1 + 0.05 * pow(e, -0.072 * (abs(value) - 90))) - 0.764) / 1.13576986016) + 0.035) / 1.02982298422;
	} else {
		output = 0;
	}
	return output;
}

int t = 0;
int mode = 0;
int larm;

task main() {
	setup();
	while (true) {
		t++;
		larm = getMotorEncoder(armleft);
		setTouchLEDColor(color2, colorRed);
		setTouchLEDColor(color4, colorRed);
		setTouchLEDColor(color1, colorYellow);
		setTouchLEDColor(color3, colorYellow);
		if (getMotorSpeed(leftdrive) < 0 && getMotorSpeed(rightdrive) < 0) {
			if (((t / 300) % 2) == 1) {
				setTouchLEDColor(color2, colorRed);
				setTouchLEDColor(color4, colorRed);
			} else {
				setTouchLEDRGB(color2, 0, 0, 0);
				setTouchLEDRGB(color4, 0, 0, 0);
			}
		}
		if (getJoystickValue(BtnFDown) == 1) {
			playSound(soundGasFillup);
		} else if (getJoystickValue(BtnEUp) == 1) {
			playSound(soundTada);
		} else if (getJoystickValue(BtnEDown) == 1) {
			playSound(soundWrongWay);
		}

		if (getMotorSpeed(leftdrive) > 0 && getMotorSpeed(rightdrive) > 0) {
			setTouchLEDColor(color2, colorRed);
			setTouchLEDColor(color4, colorRed);
			setTouchLEDColor(color1, colorYellow);
			setTouchLEDColor(color3, colorYellow);
		}
		if (getMotorSpeed(leftdrive) < 0 && getMotorSpeed(rightdrive) > 0) {
			if (((t / 300) % 2) == 1) {
				setTouchLEDColor(color3, colorYellow);
				setTouchLEDColor(color2, colorRed);
			} else {
				setTouchLEDRGB(color3, 0, 0, 0);
				setTouchLEDRGB(color2, 0, 0, 0);
			}
		}
		if (getMotorSpeed(leftdrive) > 0 && getMotorSpeed(rightdrive) < 0) {
			if (((t / 300) % 2) == 1) {
				setTouchLEDColor(color1, colorYellow);
				setTouchLEDColor(color4, colorRed);
			} else {
				setTouchLEDRGB(color1, 0, 0, 0);
				setTouchLEDRGB(color4, 0, 0, 0);
			}
		}
		displayCenteredTextLine(1, "%d", larm);
		setMotorSpeed(leftdrive, map(getJoystickValue(ChA)));
		setMotorSpeed(rightdrive, map(getJoystickValue(ChD)));
		setMotorSpeed(strafe, 0.5 * getJoystickValue(ChB) + 0.5 * getJoystickValue(ChC));
		if (getJoystickValue(BtnFUp) == 1) {
			setup();
		}
		if (getJoystickValue(BtnLUp) == 1 && getJoystickValue(BtnLDown) == 0 && getMotorEncoder(armleft) < 340) {
			setMotorSpeed(armleft, 80);
			setMotorSpeed(armright, 80);
		} else if (getJoystickValue(BtnLDown) == 1 && getJoystickValue(BtnLUp) == 0) {
			setMotorSpeed(armleft, -80);
			setMotorSpeed(armright, -80);
		} else {
			setMotorSpeed(armleft, 0);
			setMotorSpeed(armright, 0);
		}
		if (getJoystickValue(BtnEUp) == 1) {
			mode = 0;
		} else if (getJoystickValue(BtnEDown) == 1) {
			mode = 1;
		}
		/*
		if (getJoystickValue(BtnRUp) == 1 && getJoystickValue(BtnRDown) == 0) {
			setMotorSpeed(claw, 100);
		} else if (getJoystickValue(BtnRDown) == 1 && getJoystickValue(BtnRUp) == 0) {
			setMotorSpeed(claw, -100);
		} else {
			setMotorSpeed(claw, 0);
		}
		*/

	}
}
