#pragma config(Sensor, port1,  color2,         sensorVexIQ_LED)
#pragma config(Sensor, port2,  color1,         sensorVexIQ_LED)
#pragma config(Sensor, port3,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port4,  color3,         sensorVexIQ_LED)
#pragma config(Sensor, port11, color4,         sensorVexIQ_LED)
#pragma config(Sensor, port12, color5,         sensorVexIQ_LED)
#pragma config(Motor,  motor5,          arm,           tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          backarm,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor7,          strafe,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          rightdrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor9,          leftdrive,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor10,         spintake,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Match 1 103 points
*/

float e = 2.71828459045;
int k = 400;
bool gear = true;
int apos = 0;

int dropDelay = 250;

bool sucking = false;
bool barfing = false;

task moveArm() {
	while (true) {
		if (getJoystickValue(BtnLUp) == 1 && apos == 0) {
			apos = 1;
			moveMotorTarget(arm, 1200, 100);
			waitUntilMotorStop(arm);
		} else if (getJoystickValue(BtnLUp) == 1 && apos == 1) {
			apos = 2;
			moveMotorTarget(arm, 1600, 100);
			waitUntilMotorStop(arm);
		}
		if (getJoystickValue(BtnLDown) == 1) {
			apos = 0;
		}
	}
}

void JingleBells()
{
  //        112 = Tempo
  //          5 = Default octave
  //     Eighth = Default note length
  //        10% = Break between notes
  //
  wait1Msec( 134);  // Note(Rest, Duration(32th))
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteE, octave2,   96); wait1Msec(1071);  // Note(A, Duration(Quarter))
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteE, octave2,   96); wait1Msec(1071);  // Note(A, Duration(Quarter))
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteG, octave2,   48); wait1Msec( 536);  // Note(C6)
  playNote(  NoteC, octave2,   72); wait1Msec( 804);  // Note(F, Duration(Eighth .))
  playNote(  NoteD, octave2,   24); wait1Msec( 268);  // Note(G, Duration(16th))
  playNote(  NoteE, octave2,  193); wait1Msec(2143);  // Note(A, Duration(Half))
  playNote(  NoteF, octave2,   48); wait1Msec( 536);  // Note(A#)
  playNote(  NoteF, octave2,   48); wait1Msec( 536);  // Note(A#)
  playNote(  NoteF, octave2,   72); wait1Msec( 804);  // Note(A#, Duration(Eighth .))
  playNote(  NoteF, octave2,   24); wait1Msec( 268);  // Note(A#, Duration(16th))
  playNote(  NoteF, octave2,   48); wait1Msec( 536);  // Note(A#)
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteE, octave2,   72); wait1Msec( 804);  // Note(A, Duration(Eighth .))
  playNote(  NoteE, octave2,   24); wait1Msec( 268);  // Note(A, Duration(16th))
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteD, octave2,   48); wait1Msec( 536);  // Note(G)
  playNote(  NoteD, octave2,   48); wait1Msec( 536);  // Note(G)
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteD, octave2,   96); wait1Msec(1071);  // Note(G, Duration(Quarter))
  playNote(  NoteG, octave2,   96); wait1Msec(1071);  // Note(C6, Duration(Quarter))
  wait1Msec( 134);  // Note(Rest, Duration(32th))
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteE, octave2,   96); wait1Msec(1071);  // Note(A, Duration(Quarter))
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteE, octave2,   96); wait1Msec(1071);  // Note(A, Duration(Quarter))
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteG, octave1,   48); wait1Msec( 536);  // Note(C6)
  playNote(  NoteC, octave2,   72); wait1Msec( 804);  // Note(F, Duration(Eighth .))
  playNote(  NoteD, octave2,   24); wait1Msec( 268);  // Note(G, Duration(16th))
  playNote(  NoteE, octave2,  193); wait1Msec(2143);  // Note(A, Duration(Half))
  playNote(  NoteF, octave2,   48); wait1Msec( 536);  // Note(A#)
  playNote(  NoteF, octave2,   48); wait1Msec( 536);  // Note(A#)
  playNote(  NoteF, octave2,   72); wait1Msec( 804);  // Note(A#, Duration(Eighth .))
  playNote(  NoteF, octave2,   24); wait1Msec( 268);  // Note(A#, Duration(16th))
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A#)
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteE, octave2,   72); wait1Msec( 804);  // Note(A, Duration(Eighth .))
  playNote(  NoteE, octave2,   24); wait1Msec( 268);  // Note(A, Duration(16th))
  playNote(  NoteG, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteG, octave2,   48); wait1Msec( 536);  // Note(G)
  playNote(  NoteE, octave2,   48); wait1Msec( 536);  // Note(G)
  playNote(  NoteD, octave2,   48); wait1Msec( 536);  // Note(A)
  playNote(  NoteC, octave2,   96); wait1Msec(1071);  // Note(G, Duration(Quarter)
  return;
}


void setup() {
	setMotorSpeed(leftdrive, 0);
	setMotorSpeed(rightdrive, 0);
	setMotorSpeed(strafe, 0);
	setMotorSpeed(arm, 0);
	setMotorSpeed(backarm, 0);
	setMotorSpeed(spintake, 0);
	resetMotorEncoder(arm);
	resetMotorEncoder(strafe);
	resetMotorEncoder(rightdrive);
	resetMotorEncoder(leftdrive);
	resetMotorEncoder(backarm);
	resetMotorEncoder(spintake);
	setGyroSensitivity(gyro, gyroNormalSensitivity);
	resetGyro(gyro);
}

void driveReset() {
	setMotorSpeed(leftdrive, 0);
	setMotorSpeed(rightdrive, 0);
	setMotorSpeed(strafe, 0);
	resetMotorEncoder(rightdrive);
	resetMotorEncoder(leftdrive);
	resetMotorEncoder(strafe);
}



int mapFast(int value) {
	float A = 633.992;
	float C = -4.36118;
	float b = -5.4813;
	float c = 101.126;
	float k = -1.90005;
	float a = -0.0000200555;
	float n = 2.66124;
	float power = -a * pow(value - b, n);
	float denominator = k + C * pow(e, power);
	return value != 0 ? round((A / denominator + c) * (abs(value) / value)) : 0;
}

int mapSlow(int value) {
	float A = 380.95;
	float C = -4.36118;
	float b = -5.4813;
	float c = 60.6755;
	float k = -1.90005;
	float a = -0.0000200555;
	float n = 2.66124;
	float power = -a * pow(value - b, n);
	float denominator = k + C * pow(e, power);
	return value != 0 ? round((A / denominator + c) * (abs(value) / value)) : 0;
}

int t = 0;
int mode = 0;
int larm;

int sign(int value) {
	return value == 0 ? 0 : abs(value) / value;
}

int leftspeed;
int rightspeed;

int released1 = 0;
int released2 = 0;

int temp = 0;
int spintakedirection = 0;

task music() {
	while (true) {
		if (getJoystickValue(BtnFUp) == 1) {
			JingleBells();
		}
	}
}

task main() {
	setup();
	setTouchLEDColor(color1, colorViolet);
	setTouchLEDColor(color2, colorViolet);
	while (true) {
		larm = getMotorEncoder(arm);
		if (mode == 0) {
		t++;
			if (t < k) {
				setTouchLEDColor(color1, colorRed);
				setTouchLEDColor(color2, colorGreen);
				setTouchLEDColor(color3, colorGreen);
				setTouchLEDColor(color4, colorRed);
			} else if (t < k * 2) {
				setTouchLEDColor(color1, colorGreen);
				setTouchLEDColor(color2, colorRed);
				setTouchLEDColor(color3, colorRed);
				setTouchLEDColor(color4, colorGreen);
			}
			if (t < k / 2) {
				setTouchLEDColor(color5, colorRed);
			} else if (t < k) {
				setTouchLEDColor(color5, colorGreen);
			} else if (t < k * 3 / 2) {
				setTouchLEDColor(color5, colorRed);
			} else {
				setTouchLEDColor(color5, colorGreen);
			}
			if (t > 798) {
				t = 0;
			}
		}


		displayCenteredTextLine(1, "%d", getMotorEncoder(backarm));

		setMotorSpeed(strafe, (0.5 * abs(getJoystickValue(ChB)) >= 40 ? getJoystickValue(ChB) : 0 + 0.5 * abs(getJoystickValue(ChC)) >= 40 ? getJoystickValue(ChC) : 0) * 0.4);

		if (getJoystickValue(BtnFUp) == 1) {
			setup();
		}

		if (getJoystickValue(BtnLUp) == 1 && getJoystickValue(BtnLDown) == 0) {
			setMotorSpeed(arm, 100);
			if (getMotorEncoder(arm) < 600) {
				setMotorSpeed(spintake, -40);
				spintakedirection = 0;
			}
		} else if (getJoystickValue(BtnLDown) == 1 && getJoystickValue(BtnLUp) == 0) {
			setMotorSpeed(arm, -100);
			setMotorSpeed(spintake, 40);
			spintakedirection = 0;
		} else {
			setMotorSpeed(arm, 0);
			if (spintakedirection == 0) {
				setMotorSpeed(spintake, 0);
			}
		}

		if (getJoystickValue(BtnEUp) == 1 && getJoystickValue(BtnEDown) == 0) {
			setMotorSpeed(spintake, 100);
			spintakedirection = 1;
		} else if (getJoystickValue(BtnEDown) == 1 && getJoystickValue(BtnEUp) == 0) {
			setMotorSpeed(spintake, -100);
			spintakedirection = -1;
		} else if (getJoystickValue(BtnEUp) == 1 && getJoystickValue(BtnEDown) == 1) {
			setMotorSpeed(spintake, 0);
			spintakedirection = 0;
		}

		if (getJoystickValue(BtnRDown) == 1 && getJoystickValue(BtnRUp) == 0) {
			setMotorSpeed(backarm, 100);
		} else if (getJoystickValue(BtnRUp) == 1 && getJoystickValue(BtnRDown) == 0) {
			setMotorSpeed(backarm, -100);
		} else {
			setMotorSpeed(backarm, 0);
		}

		leftspeed = getJoystickValue(ChA) * getJoystickValue(ChA) * getJoystickValue(ChA) / 10000 * (gear ? 1 : 0.6);
		rightspeed = getJoystickValue(ChD) * getJoystickValue(ChD) * getJoystickValue(ChD) / 10000 * (gear ? 1 : 0.6);

		if (sign(leftspeed) == sign(rightspeed) && abs(leftspeed - rightspeed) < (getJoystickValue(BtnLUp) == 1 ? 50 : 30)) {
			temp = leftspeed * 0.5 + rightspeed * 0.5;
			leftspeed = temp;
			rightspeed = temp;
		}
		if (getMotorSpeed(strafe) > 50 && abs(leftspeed) < 70 && abs(rightspeed) < 70) {
			leftspeed = 0;
			rightspeed = 0;
		}
		setMotorSpeed(leftdrive, leftspeed);
		setMotorSpeed(rightdrive, rightspeed);

	}
}
