#pragma config(Sensor, port1,  color2,         sensorVexIQ_LED)
#pragma config(Sensor, port2,  color1,         sensorVexIQ_LED)
#pragma config(Sensor, port3,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port4,  color3,         sensorVexIQ_LED)
#pragma config(Sensor, port11, color4,         sensorVexIQ_LED)
#pragma config(Sensor, port12, color5,         sensorVexIQ_LED)
#pragma config(Motor,  motor5,          arm,           tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          backarm,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor7,          strafe,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          rightdrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor9,          leftdrive,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor10,         spintake,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float e = 2.71828459045;
int k = 4000;
bool gear = true;

int dropDelay = 250;

bool sucking = false;
bool barfing = false;

void setup() {
	setMotorSpeed(leftdrive, 0);
	setMotorSpeed(rightdrive, 0);
	setMotorSpeed(strafe, 0);
	setMotorSpeed(arm, 0);
	setMotorSpeed(backarm, 0);
	setMotorSpeed(spintake, 0);
	resetMotorEncoder(arm);
	resetMotorEncoder(strafe);
	resetMotorEncoder(rightdrive);
	resetMotorEncoder(leftdrive);
	resetMotorEncoder(backarm);
	resetMotorEncoder(spintake);
	setGyroSensitivity(gyro, gyroNormalSensitivity);
	resetGyro(gyro);
}

void driveReset() {
	setMotorSpeed(leftdrive, 0);
	setMotorSpeed(rightdrive, 0);
	setMotorSpeed(strafe, 0);
	resetMotorEncoder(rightdrive);
	resetMotorEncoder(leftdrive);
	resetMotorEncoder(strafe);
}



int mapFast(int value) {
	float A = 633.992;
	float C = -4.36118;
	float b = -5.4813;
	float c = 101.126;
	float k = -1.90005;
	float a = -0.0000200555;
	float n = 2.66124;
	float power = -a * pow(value - b, n);
	float denominator = k + C * pow(e, power);
	return value != 0 ? round((A / denominator + c) * (abs(value) / value)) : 0;
}

int mapSlow(int value) {
	float A = 380.95;
	float C = -4.36118;
	float b = -5.4813;
	float c = 60.6755;
	float k = -1.90005;
	float a = -0.0000200555;
	float n = 2.66124;
	float power = -a * pow(value - b, n);
	float denominator = k + C * pow(e, power);
	return value != 0 ? round((A / denominator + c) * (abs(value) / value)) : 0;
}

int t = 0;
int mode = 0;
int larm;

int sign(int value) {
	return value == 0 ? 0 : abs(value) / value;
}

int leftspeed;
int rightspeed;

int released1 = 0;
int released2 = 0;

int temp = 0;
int spintakedirection = 0;

task main() {
	hogCPU();
	setup();
	setTouchLEDColor(color1, colorViolet);
	setTouchLEDColor(color2, colorViolet);
	while (true) {
		larm = getMotorEncoder(arm);
		if (mode == 0) {
		t++;
			if (t % k * 6 < k ) {
				setTouchLEDColor(color1, colorRed);
				setTouchLEDColor(color2, colorRed);
				setTouchLEDColor(color3, colorRed);
				setTouchLEDColor(color4, colorRed);
				setTouchLEDColor(color5, colorRed);
			} else if (t % k * 6 < 2 * k) {
				setTouchLEDColor(color1, colorOrange);
				setTouchLEDColor(color2, colorOrange);
				setTouchLEDColor(color3, colorOrange);
				setTouchLEDColor(color4, colorOrange);
				setTouchLEDColor(color5, colorOrange);
			} else if (t % k * 6 < 3 * k) {
				setTouchLEDColor(color1, colorYellow);
				setTouchLEDColor(color2, colorYellow);
				setTouchLEDColor(color3, colorYellow);
				setTouchLEDColor(color4, colorYellow);
				setTouchLEDColor(color5, colorYellow);
			} else if (t % k * 6 < 4 * k) {
				setTouchLEDColor(color1, colorGreen);
				setTouchLEDColor(color2, colorGreen);
				setTouchLEDColor(color3, colorGreen);
				setTouchLEDColor(color4, colorGreen);
				setTouchLEDColor(color5, colorGreen);
			} else if (t % k * 6 < 5 * k) {
				setTouchLEDColor(color1, colorBlue);
				setTouchLEDColor(color2, colorBlue);
				setTouchLEDColor(color3, colorBlue);
				setTouchLEDColor(color4, colorBlue);
				setTouchLEDColor(color5, colorBlue);
			} else {
				setTouchLEDColor(color1, colorViolet);
				setTouchLEDColor(color2, colorViolet);
				setTouchLEDColor(color3, colorViolet);
				setTouchLEDColor(color4, colorViolet);
				setTouchLEDColor(color5, colorViolet);
			}
		}


		displayCenteredTextLine(1, "%d", larm);

		setMotorSpeed(strafe, (0.5 * abs(getJoystickValue(ChB)) >= 40 ? getJoystickValue(ChB) : 0 + 0.5 * abs(getJoystickValue(ChC)) >= 40 ? getJoystickValue(ChC) : 0) * 0.5);

		if (getJoystickValue(BtnFUp) == 1) {
			setup();
		}

		if (getJoystickValue(BtnLUp) == 1 && getJoystickValue(BtnLDown) == 0) {
			setMotorSpeed(arm, 100);
			if (getMotorEncoder(arm) < 600) {
				setMotorSpeed(spintake, -40);
				spintakedirection = 0;
			}
		} else if (getJoystickValue(BtnLDown) == 1 && getJoystickValue(BtnLUp) == 0 && (getMotorEncoder(arm) > 10 || getJoystickValue(BtnFUp) == 1)) {
			setMotorSpeed(arm, -100);
			setMotorSpeed(spintake, 40);
			spintakedirection = 0;
		} else {
			setMotorSpeed(arm, 0);
			if (spintakedirection == 0) {
				setMotorSpeed(spintake, 0);
			}
		}

		if (getJoystickValue(BtnEUp) == 1 && getJoystickValue(BtnEDown) == 0) {
			setMotorSpeed(spintake, 100);
			spintakedirection = 1;
		} else if (getJoystickValue(BtnEDown) == 1 && getJoystickValue(BtnEUp) == 0) {
			setMotorSpeed(spintake, -100);
			spintakedirection = -1;
		} else if (getJoystickValue(BtnEUp) == 1 && getJoystickValue(BtnEDown) == 1) {
			setMotorSpeed(spintake, 0);
			spintakedirection = 0;
		}

		if (getJoystickValue(BtnRDown) == 1 && getJoystickValue(BtnRUp) == 0) {
			setMotorSpeed(backarm, 100);
		} else if (getJoystickValue(BtnRUp) == 1 && getJoystickValue(BtnRDown) == 0) {
			setMotorSpeed(backarm, -100);
		} else {
			setMotorSpeed(backarm, 0);
		}

		leftspeed = getJoystickValue(ChA) * getJoystickValue(ChA) * getJoystickValue(ChA) / 10000 * (gear ? 1 : 0.6);
		rightspeed = getJoystickValue(ChD) * getJoystickValue(ChD) * getJoystickValue(ChD) / 10000 * (gear ? 1 : 0.6);

		if (sign(leftspeed) == sign(rightspeed) && abs(leftspeed - rightspeed) < (getJoystickValue(BtnLUp) == 1 ? 50 : 30)) {
			temp = leftspeed * 0.5 + rightspeed * 0.5;
			leftspeed = temp;
			rightspeed = temp;
		}
		if (getMotorSpeed(strafe) > 50 && abs(leftspeed) < 70 && abs(rightspeed) < 70) {
			leftspeed = 0;
			rightspeed = 0;
		}
		setMotorSpeed(leftdrive, leftspeed);
		setMotorSpeed(rightdrive, rightspeed);

	}
}
